# Generated by Django 5.2.6 on 2026-07-27 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=5)),
                ('preferred_foot', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('BOTH', 'Both')], default='RIGHT', max_length=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['team', 'jersey_number'],
                'indexes': [models.Index(fields=['team'], name='players_team_id_483bc4_idx'), models.Index(fields=['name'], name='players_name_0574eb_idx'), models.Index(fields=['position'], name='players_positio_0bd0a3_idx')],
                'unique_together': {('team', 'jersey_number')},
            },
        ),
    ]
