"""
Identity Visual Validation V5.2.

Validates the output of the GlobalIdentityManager V5.2
without performing identity matching itself.

V5.2 changes from V5.1
----------------------

1. Matcher reasons are informational only.
   A normal matcher reason such as:
       matcher:appearance_match
       matcher:geometry_match
       matcher:accepted
   no longer makes an accepted match suspicious.

2. Suspicious matches are based only on actual validation
   warnings generated by this validator.

3. Strong and normal accepted appearance matches with
   healthy geometry/motion remain PASS.

4. Appearance-not-evaluated is distinguished from missing
   embeddings.

5. Accepted geometry-only matches are REVIEW rather than
   automatically HIGH_RISK.

6. Weak appearance + poor geometry/motion can still become
   HIGH_RISK.

7. Team and jersey mismatches remain CRITICAL.

8. Identity-level REVIEW is now based on genuine validation
   warnings rather than merely the existence of matcher
   diagnostic metadata.

This module is intentionally read-only.

It does NOT:
    - perform detection
    - perform tracking
    - perform identity matching
    - mutate Track objects
    - mutate Identity objects
    - alter GlobalIdentityManager state

Expected matcher:
    IdentityMatcher V5.1 / V5.2

Expected manager:
    GlobalIdentityManager V5.1 / V5.2
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, Optional

from ai_engine.schemas.track import Identity, Track


logger = logging.getLogger(__name__)


# ============================================================
# VALIDATION RESULT
# ============================================================


@dataclass
class VisualValidationResult:
    """
    Result of validating one identity/match.

    status:
        PASS
        REVIEW
        HIGH_RISK
        INVALID

    risk_level:
        LOW
        MEDIUM
        HIGH
        CRITICAL
    """

    identity_id: str

    track_id: Optional[int] = None

    status: str = "PASS"

    risk_level: str = "LOW"

    reason: str = ""

    appearance_similarity: float = -1.0

    appearance_evaluated: bool = False

    temporal_gap: int = 0

    spatial_distance: float = 0.0

    motion_difference: float = 0.0

    team_match: Optional[bool] = None

    jersey_match: Optional[bool] = None

    score: float = 0.0

    matched: bool = False

    reasons: list[str] = field(default_factory=list)

    # --------------------------------------------------------
    # V5.2
    # --------------------------------------------------------
    # Matcher reasons are kept separately from actual
    # validation warnings.
    #
    # This prevents informational matcher diagnostics from
    # turning a healthy accepted match into "suspicious".
    # --------------------------------------------------------

    matcher_reasons: list[str] = field(
        default_factory=list
    )

    validation_warnings: list[str] = field(
        default_factory=list
    )

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the validation result into a JSON-safe
        dictionary.
        """

        return {
            "identity_id": self.identity_id,
            "track_id": self.track_id,
            "status": self.status,
            "risk_level": self.risk_level,
            "reason": self.reason,

            "appearance_similarity": float(
                self.appearance_similarity
            ),

            "appearance_evaluated": bool(
                self.appearance_evaluated
            ),

            "temporal_gap": int(
                self.temporal_gap
            ),

            "spatial_distance": float(
                self.spatial_distance
            ),

            "motion_difference": float(
                self.motion_difference
            ),

            "team_match": self.team_match,
            "jersey_match": self.jersey_match,

            "score": float(self.score),

            "matched": bool(
                self.matched
            ),

            "reasons": list(
                self.reasons
            ),

            "matcher_reasons": list(
                self.matcher_reasons
            ),

            "validation_warnings": list(
                self.validation_warnings
            ),
        }


# ============================================================
# IDENTITY VALIDATION RESULT
# ============================================================


@dataclass
class IdentityValidationResult:
    """
    Validation result for one global identity.
    """

    identity_id: str

    class_name: Optional[str] = None

    source_track_count: int = 0

    source_track_ids: list[Any] = field(
        default_factory=list
    )

    observation_count: int = 0

    first_frame: Optional[int] = None

    last_frame: Optional[int] = None

    team: Any = None

    jersey_number: Any = None

    status: str = "PASS"

    risk_level: str = "LOW"

    reasons: list[str] = field(
        default_factory=list
    )

    accepted_matches: int = 0

    rejected_matches: int = 0

    appearance_matches: int = 0

    strong_appearance_matches: int = 0

    weak_appearance_matches: int = 0

    missing_embeddings: int = 0

    risky_matches: int = 0

    suspicious_matches: int = 0

    validation_warning_count: int = 0

    matcher_diagnostic_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        """
        Convert into a JSON-safe dictionary.
        """

        return {
            "identity_id": self.identity_id,

            "class_name": self.class_name,

            "source_track_count": (
                self.source_track_count
            ),

            "source_track_ids": list(
                self.source_track_ids
            ),

            "observation_count": (
                self.observation_count
            ),

            "first_frame": self.first_frame,

            "last_frame": self.last_frame,

            "team": self.team,

            "jersey_number": self.jersey_number,

            "status": self.status,

            "risk_level": self.risk_level,

            "reasons": list(
                self.reasons
            ),

            "accepted_matches": (
                self.accepted_matches
            ),

            "rejected_matches": (
                self.rejected_matches
            ),

            "appearance_matches": (
                self.appearance_matches
            ),

            "strong_appearance_matches": (
                self.strong_appearance_matches
            ),

            "weak_appearance_matches": (
                self.weak_appearance_matches
            ),

            "missing_embeddings": (
                self.missing_embeddings
            ),

            "risky_matches": (
                self.risky_matches
            ),

            "suspicious_matches": (
                self.suspicious_matches
            ),

            "validation_warning_count": (
                self.validation_warning_count
            ),

            "matcher_diagnostic_count": (
                self.matcher_diagnostic_count
            ),
        }


# ============================================================
# VISUAL VALIDATOR
# ============================================================


class IdentityVisualValidator:
    """
    Validate GlobalIdentityManager V5.2 results.

    The validator uses the same appearance thresholds as
    IdentityMatcher V5.1/V5.2 by default:

        minimum = 0.72
        normal  = 0.78
        strong  = 0.85

    It does not change matcher decisions.

    It only reports whether accepted matches look healthy,
    questionable, or risky.

    V5.2 IMPORTANT:

    Matcher diagnostic reasons are informational.

    They do NOT automatically make a match suspicious.

    Only validation warnings generated by this class affect
    suspicious/risk calculations.
    """

    VERSION = "v5.2"

    STATUS_PASS = "PASS"
    STATUS_REVIEW = "REVIEW"
    STATUS_HIGH_RISK = "HIGH_RISK"
    STATUS_INVALID = "INVALID"

    RISK_LOW = "LOW"
    RISK_MEDIUM = "MEDIUM"
    RISK_HIGH = "HIGH"
    RISK_CRITICAL = "CRITICAL"

    def __init__(
        self,
        minimum_appearance_similarity: float = 0.72,
        normal_appearance_similarity: float = 0.78,
        strong_appearance_similarity: float = 0.85,

        weak_spatial_ratio: float = 0.20,
        weak_motion_ratio: float = 0.25,

        strong_spatial_ratio: float = 0.35,
        strong_motion_ratio: float = 0.40,

        long_gap_ratio: float = 0.50,

        max_temporal_gap: int = 75,
        max_spatial_distance: float = 300.0,
        max_motion_difference: float = 80.0,
    ) -> None:

        # ----------------------------------------------------
        # Validate thresholds
        # ----------------------------------------------------

        thresholds = (
            minimum_appearance_similarity,
            normal_appearance_similarity,
            strong_appearance_similarity,
        )

        if any(
            not 0.0 <= value <= 1.0
            for value in thresholds
        ):
            raise ValueError(
                "Appearance thresholds must be "
                "between 0 and 1."
            )

        if not (
            minimum_appearance_similarity
            <= normal_appearance_similarity
            <= strong_appearance_similarity
        ):
            raise ValueError(
                "Appearance thresholds must satisfy "
                "minimum <= normal <= strong."
            )

        ratios = (
            weak_spatial_ratio,
            weak_motion_ratio,
            strong_spatial_ratio,
            strong_motion_ratio,
            long_gap_ratio,
        )

        if any(
            not 0.0 <= value <= 1.0
            for value in ratios
        ):
            raise ValueError(
                "Validation ratios must be "
                "between 0 and 1."
            )

        if max_temporal_gap < 0:
            raise ValueError(
                "max_temporal_gap must be >= 0."
            )

        if max_spatial_distance <= 0:
            raise ValueError(
                "max_spatial_distance must be > 0."
            )

        if max_motion_difference <= 0:
            raise ValueError(
                "max_motion_difference must be > 0."
            )

        # ----------------------------------------------------
        # Threshold configuration
        # ----------------------------------------------------

        self.minimum_appearance_similarity = float(
            minimum_appearance_similarity
        )

        self.normal_appearance_similarity = float(
            normal_appearance_similarity
        )

        self.strong_appearance_similarity = float(
            strong_appearance_similarity
        )

        self.weak_spatial_ratio = float(
            weak_spatial_ratio
        )

        self.weak_motion_ratio = float(
            weak_motion_ratio
        )

        self.strong_spatial_ratio = float(
            strong_spatial_ratio
        )

        self.strong_motion_ratio = float(
            strong_motion_ratio
        )

        self.long_gap_ratio = float(
            long_gap_ratio
        )

        self.max_temporal_gap = int(
            max_temporal_gap
        )

        self.max_spatial_distance = float(
            max_spatial_distance
        )

        self.max_motion_difference = float(
            max_motion_difference
        )

        # ----------------------------------------------------
        # Runtime state
        # ----------------------------------------------------

        self.match_results: list[
            VisualValidationResult
        ] = []

        self.identity_results: dict[
            str,
            IdentityValidationResult,
        ] = {}

        self.reset()

    # ========================================================
    # RESET
    # ========================================================

    def reset(self) -> None:
        """
        Reset all validation results.
        """

        self.match_results = []

        self.identity_results = {}

    # ========================================================
    # PUBLIC API
    # ========================================================

    def validate_manager(
        self,
        manager: Any,
    ) -> dict[str, Any]:
        """
        Validate an entire GlobalIdentityManager.

        The manager is treated as read-only.
        """

        self.reset()

        diagnostics = list(
            getattr(
                manager,
                "match_diagnostics",
                [],
            )
        )

        identities = getattr(
            manager,
            "identities",
            {},
        )

        self.validate_diagnostics(
            diagnostics
        )

        for identity_id, identity in identities.items():

            self._validate_identity(
                identity_id,
                identity,
            )

        return self.get_report()

    # ========================================================

    def validate_diagnostics(
        self,
        diagnostics: Iterable[dict[str, Any]],
    ) -> list[VisualValidationResult]:
        """
        Validate manager match diagnostics.

        Expected diagnostic fields come directly from
        GlobalIdentityManager._record_match_diagnostic().
        """

        results = []

        for diagnostic in diagnostics:

            result = (
                self._validate_diagnostic(
                    diagnostic
                )
            )

            self.match_results.append(
                result
            )

            results.append(
                result
            )

        return results

    # ========================================================
    # SINGLE DIAGNOSTIC
    # ========================================================

    def _validate_diagnostic(
        self,
        diagnostic: dict[str, Any],
    ) -> VisualValidationResult:
        """
        Validate one match diagnostic.
        """

        identity_id = str(
            diagnostic.get(
                "identity_id",
                "UNKNOWN",
            )
        )

        track_id = diagnostic.get(
            "track_id"
        )

        matched = bool(
            diagnostic.get(
                "matched",
                False,
            )
        )

        score = self._safe_float(
            diagnostic.get(
                "score",
                0.0,
            ),
            default=0.0,
        )

        temporal_gap = self._safe_int(
            diagnostic.get(
                "temporal_gap",
                0,
            ),
            default=0,
        )

        spatial_distance = self._safe_float(
            diagnostic.get(
                "spatial_distance",
                0.0,
            ),
            default=0.0,
        )

        motion_difference = self._safe_float(
            diagnostic.get(
                "motion_difference",
                0.0,
            ),
            default=0.0,
        )

        appearance_similarity = self._safe_float(
            diagnostic.get(
                "appearance_similarity",
                -1.0,
            ),
            default=-1.0,
        )

        appearance_evaluated = bool(
            diagnostic.get(
                "appearance_evaluated",
                False,
            )
        )

        team_match = diagnostic.get(
            "team_match"
        )

        jersey_match = diagnostic.get(
            "jersey_match"
        )

        matcher_reason = str(
            diagnostic.get(
                "reason",
                "",
            )
            or ""
        )

        # ----------------------------------------------------
        # Separate matcher information from validator
        # warnings.
        # ----------------------------------------------------

        matcher_reasons: list[str] = []

        if matcher_reason:
            matcher_reasons.append(
                matcher_reason
            )

        validation_warnings: list[str] = []

        # ----------------------------------------------------
        # Basic diagnostic consistency
        # ----------------------------------------------------

        if (
            appearance_evaluated
            and appearance_similarity < 0.0
        ):
            validation_warnings.append(
                "appearance_evaluated_but_unavailable"
            )

        if (
            not appearance_evaluated
            and appearance_similarity >= 0.0
        ):
            validation_warnings.append(
                "appearance_similarity_without_evaluation"
            )

        # ----------------------------------------------------
        # Appearance classification
        # ----------------------------------------------------

        appearance_category = (
            self._appearance_category(
                appearance_similarity,
                appearance_evaluated,
            )
        )

        if (
            matched
            and appearance_category == "weak"
        ):
            validation_warnings.append(
                "accepted_weak_appearance"
            )

        if (
            matched
            and appearance_category == "missing"
        ):
            validation_warnings.append(
                "accepted_without_appearance"
            )

        # ----------------------------------------------------
        # Geometry ratios
        # ----------------------------------------------------

        spatial_ratio = self._spatial_ratio(
            spatial_distance
        )

        motion_ratio = self._motion_ratio(
            motion_difference
        )

        # ----------------------------------------------------
        # Accepted-match validation
        # ----------------------------------------------------

        if matched:

            # ------------------------------------------------
            # Weak appearance + poor geometry
            # ------------------------------------------------

            if (
                appearance_category == "weak"
                and spatial_ratio
                > self.weak_spatial_ratio
            ):
                validation_warnings.append(
                    "weak_appearance_spatial_uncertainty"
                )

            if (
                appearance_category == "weak"
                and motion_ratio
                > self.weak_motion_ratio
            ):
                validation_warnings.append(
                    "weak_appearance_motion_uncertainty"
                )

            # ------------------------------------------------
            # Normal appearance + extremely poor geometry
            # ------------------------------------------------

            if (
                appearance_category == "normal"
                and spatial_ratio > 0.70
            ):
                validation_warnings.append(
                    "normal_appearance_high_spatial_ratio"
                )

            if (
                appearance_category == "normal"
                and motion_ratio > 0.70
            ):
                validation_warnings.append(
                    "normal_appearance_high_motion_ratio"
                )

            # ------------------------------------------------
            # Strong appearance + extreme geometry
            # ------------------------------------------------

            if (
                appearance_category == "strong"
                and spatial_ratio > 0.85
            ):
                validation_warnings.append(
                    "strong_appearance_extreme_spatial_ratio"
                )

            if (
                appearance_category == "strong"
                and motion_ratio > 0.90
            ):
                validation_warnings.append(
                    "strong_appearance_extreme_motion_ratio"
                )

            # ------------------------------------------------
            # Temporal gap
            # ------------------------------------------------

            if (
                temporal_gap
                >= (
                    self.max_temporal_gap
                    * self.long_gap_ratio
                )
            ):
                validation_warnings.append(
                    "accepted_long_temporal_gap"
                )

            # ------------------------------------------------
            # Team mismatch
            # ------------------------------------------------

            if team_match is False:
                validation_warnings.append(
                    "accepted_team_mismatch"
                )

            # ------------------------------------------------
            # Jersey mismatch
            # ------------------------------------------------

            if jersey_match is False:
                validation_warnings.append(
                    "accepted_jersey_mismatch"
                )

        # ----------------------------------------------------
        # Rejected diagnostic consistency
        # ----------------------------------------------------

        if not matched:

            if (
                team_match is False
            ):
                validation_warnings.append(
                    "rejected_team_mismatch"
                )

            if (
                jersey_match is False
            ):
                validation_warnings.append(
                    "rejected_jersey_mismatch"
                )

        # ----------------------------------------------------
        # Combined reasons
        # ----------------------------------------------------

        reasons = (
            list(validation_warnings)
            + [
                f"matcher:{reason}"
                for reason in matcher_reasons
            ]
        )

        # ----------------------------------------------------
        # Determine risk
        # ----------------------------------------------------

        risk_level = self._calculate_risk(
            matched=matched,
            appearance_category=(
                appearance_category
            ),
            appearance_similarity=(
                appearance_similarity
            ),
            appearance_evaluated=(
                appearance_evaluated
            ),
            temporal_gap=temporal_gap,
            spatial_ratio=spatial_ratio,
            motion_ratio=motion_ratio,
            team_match=team_match,
            jersey_match=jersey_match,
            reasons=validation_warnings,
        )

        status = self._status_from_risk(
            risk_level
        )

        reason = self._primary_reason(
            validation_warnings,
            matched,
        )

        return VisualValidationResult(
            identity_id=identity_id,

            track_id=track_id,

            status=status,

            risk_level=risk_level,

            reason=reason,

            appearance_similarity=(
                appearance_similarity
            ),

            appearance_evaluated=(
                appearance_evaluated
            ),

            temporal_gap=temporal_gap,

            spatial_distance=(
                spatial_distance
            ),

            motion_difference=(
                motion_difference
            ),

            team_match=team_match,

            jersey_match=jersey_match,

            score=score,

            matched=matched,

            reasons=reasons,

            matcher_reasons=matcher_reasons,

            validation_warnings=(
                validation_warnings
            ),
        )

    # ========================================================
    # IDENTITY VALIDATION
    # ========================================================

    def validate_identity(
        self,
        identity: Identity,
    ) -> IdentityValidationResult:
        """
        Validate a single Identity object.
        """

        identity_id = str(
            identity.identity_id
        )

        return self._validate_identity(
            identity_id,
            identity,
        )

    # ========================================================

    def _validate_identity(
        self,
        identity_id: str,
        identity: Identity,
    ) -> IdentityValidationResult:
        """
        Validate the composition of one global identity.
        """

        source_track_ids = list(
            getattr(
                identity,
                "source_track_ids",
                [],
            )
            or []
        )

        observations = list(
            getattr(
                identity,
                "observations",
                [],
            )
            or []
        )

        result = IdentityValidationResult(
            identity_id=str(
                identity_id
            ),

            class_name=getattr(
                identity,
                "class_name",
                None,
            ),

            source_track_count=len(
                source_track_ids
            ),

            source_track_ids=source_track_ids,

            observation_count=len(
                observations
            ),

            first_frame=getattr(
                identity,
                "first_frame",
                None,
            ),

            last_frame=getattr(
                identity,
                "last_frame",
                None,
            ),

            team=getattr(
                identity,
                "team",
                None,
            ),

            jersey_number=getattr(
                identity,
                "jersey_number",
                None,
            ),
        )

        # ----------------------------------------------------
        # Basic identity validity
        # ----------------------------------------------------

        if not source_track_ids:

            result.reasons.append(
                "identity_has_no_source_tracks"
            )

        if not observations:

            result.reasons.append(
                "identity_has_no_observations"
            )

        if (
            result.first_frame is not None
            and result.last_frame is not None
            and result.last_frame
            < result.first_frame
        ):

            result.reasons.append(
                "identity_frame_range_invalid"
            )

        # ----------------------------------------------------
        # Collect match diagnostics belonging
        # to this identity.
        # ----------------------------------------------------

        identity_matches = [
            match
            for match in self.match_results
            if match.identity_id
            == str(identity_id)
        ]

        result.accepted_matches = sum(
            1
            for match in identity_matches
            if match.matched
        )

        result.rejected_matches = sum(
            1
            for match in identity_matches
            if not match.matched
        )

        result.matcher_diagnostic_count = len(
            identity_matches
        )

        # ----------------------------------------------------
        # Appearance statistics
        # ----------------------------------------------------

        result.appearance_matches = sum(
            1
            for match in identity_matches
            if (
                match.appearance_evaluated
                and match.appearance_similarity
                >= self.minimum_appearance_similarity
            )
        )

        result.strong_appearance_matches = sum(
            1
            for match in identity_matches
            if (
                match.appearance_evaluated
                and match.appearance_similarity
                >= self.strong_appearance_similarity
            )
        )

        result.weak_appearance_matches = sum(
            1
            for match in identity_matches
            if (
                match.appearance_evaluated
                and self.minimum_appearance_similarity
                <= match.appearance_similarity
                < self.normal_appearance_similarity
            )
        )

        result.missing_embeddings = sum(
            1
            for match in identity_matches
            if (
                match.appearance_evaluated
                and match.appearance_similarity
                < 0.0
            )
        )

        # ----------------------------------------------------
        # V5.2:
        # Count ONLY actual validator warnings.
        # Matcher diagnostic reasons do NOT count.
        # ----------------------------------------------------

        result.validation_warning_count = sum(
            len(
                match.validation_warnings
            )
            for match in identity_matches
        )

        result.suspicious_matches = sum(
            1
            for match in identity_matches
            if (
                match.matched
                and match.validation_warnings
            )
        )

        result.risky_matches = sum(
            1
            for match in identity_matches
            if (
                match.matched
                and match.risk_level
                in {
                    self.RISK_HIGH,
                    self.RISK_CRITICAL,
                }
            )
        )

        # ----------------------------------------------------
        # Identity-level risk reasons
        # ----------------------------------------------------

        identity_risk_reasons = []

        if result.risky_matches > 0:

            identity_risk_reasons.append(
                "contains_risky_matches"
            )

        if result.suspicious_matches > 0:

            identity_risk_reasons.append(
                "contains_suspicious_matches"
            )

        if (
            result.weak_appearance_matches
            > 0
        ):

            identity_risk_reasons.append(
                "contains_weak_appearance_matches"
            )

        if (
            result.missing_embeddings
            > 0
        ):

            identity_risk_reasons.append(
                "contains_missing_embeddings"
            )

        result.reasons.extend(
            identity_risk_reasons
        )

        # ----------------------------------------------------
        # Identity-level risk
        # ----------------------------------------------------

        if (
            "identity_has_no_source_tracks"
            in result.reasons
            or
            "identity_has_no_observations"
            in result.reasons
            or
            "identity_frame_range_invalid"
            in result.reasons
        ):

            result.risk_level = (
                self.RISK_CRITICAL
            )

        elif result.risky_matches > 0:

            result.risk_level = (
                self.RISK_HIGH
            )

        elif (
            result.suspicious_matches > 0
            or
            result.weak_appearance_matches > 0
            or
            result.missing_embeddings > 0
        ):

            result.risk_level = (
                self.RISK_MEDIUM
            )

        else:

            result.risk_level = (
                self.RISK_LOW
            )

        result.status = (
            self._status_from_risk(
                result.risk_level
            )
        )

        self.identity_results[
            str(identity_id)
        ] = result

        return result

    # ========================================================
    # APPEARANCE CATEGORY
    # ========================================================

    def _appearance_category(
        self,
        similarity: float,
        evaluated: bool,
    ) -> str:
        """
        Classify appearance using the V5.2 threshold
        hierarchy.

        Returns:

            not_evaluated
            missing
            mismatch
            weak
            normal
            strong
        """

        if not evaluated:
            return "not_evaluated"

        if similarity < 0.0:
            return "missing"

        if (
            similarity
            < self.minimum_appearance_similarity
        ):
            return "mismatch"

        if (
            similarity
            < self.normal_appearance_similarity
        ):
            return "weak"

        if (
            similarity
            < self.strong_appearance_similarity
        ):
            return "normal"

        return "strong"

    # ========================================================
    # GEOMETRY
    # ========================================================

    def _spatial_ratio(
        self,
        distance: float,
    ) -> float:
        """
        Normalize spatial distance against the
        configured maximum spatial distance.
        """

        if distance < 0:
            return 1.0

        if distance == float("inf"):
            return 1.0

        return min(
            1.0,
            max(
                0.0,
                distance
                / self.max_spatial_distance,
            ),
        )

    # ========================================================

    def _motion_ratio(
        self,
        difference: float,
    ) -> float:
        """
        Normalize motion difference against the
        configured maximum motion difference.
        """

        if difference < 0:
            return 1.0

        if difference == float("inf"):
            return 1.0

        return min(
            1.0,
            max(
                0.0,
                difference
                / self.max_motion_difference,
            ),
        )

    # ========================================================
    # RISK
    # ========================================================

    def _calculate_risk(
        self,
        matched: bool,
        appearance_category: str,
        appearance_similarity: float,
        appearance_evaluated: bool,
        temporal_gap: int,
        spatial_ratio: float,
        motion_ratio: float,
        team_match: Optional[bool],
        jersey_match: Optional[bool],
        reasons: list[str],
    ) -> str:
        """
        Calculate validation risk.

        This does not replace IdentityMatcher's decision.

        It only determines whether an already-produced
        result deserves visual inspection.
        """

        # ----------------------------------------------------
        # Rejected matches
        # ----------------------------------------------------

        if not matched:

            # Internal inconsistency.
            if (
                "appearance_similarity_without_evaluation"
                in reasons
            ):
                return self.RISK_CRITICAL

            if (
                "appearance_evaluated_but_unavailable"
                in reasons
            ):
                return self.RISK_CRITICAL

            return self.RISK_LOW

        # ----------------------------------------------------
        # Accepted without appearance evaluation
        # ----------------------------------------------------

        if appearance_category == "not_evaluated":

            return self.RISK_MEDIUM

        # ----------------------------------------------------
        # Accepted but embedding unavailable
        # ----------------------------------------------------

        if appearance_category == "missing":

            return self.RISK_MEDIUM

        # ----------------------------------------------------
        # Accepted appearance mismatch
        # ----------------------------------------------------

        if appearance_category == "mismatch":

            return self.RISK_CRITICAL

        # ----------------------------------------------------
        # Team mismatch
        # ----------------------------------------------------

        if team_match is False:

            return self.RISK_CRITICAL

        # ----------------------------------------------------
        # Jersey mismatch
        # ----------------------------------------------------

        if jersey_match is False:

            return self.RISK_CRITICAL

        # ----------------------------------------------------
        # Long temporal gap
        # ----------------------------------------------------

        long_gap = (
            temporal_gap
            >= (
                self.max_temporal_gap
                * self.long_gap_ratio
            )
        )

        if long_gap:

            # Long gap + weak/normal appearance
            # deserves stronger review.
            if (
                appearance_similarity
                < self.normal_appearance_similarity
            ):
                return self.RISK_HIGH

            # Long gap + very poor geometry.
            if spatial_ratio > 0.70:

                return self.RISK_HIGH

            if motion_ratio > 0.70:

                return self.RISK_HIGH

            # Strong appearance with a long gap is
            # still review-worthy, but not high risk.
            return self.RISK_MEDIUM

        # ----------------------------------------------------
        # Weak appearance
        # ----------------------------------------------------

        if appearance_category == "weak":

            if (
                spatial_ratio
                > self.weak_spatial_ratio
            ):
                return self.RISK_HIGH

            if (
                motion_ratio
                > self.weak_motion_ratio
            ):
                return self.RISK_HIGH

            return self.RISK_MEDIUM

        # ----------------------------------------------------
        # Normal appearance
        # ----------------------------------------------------

        if appearance_category == "normal":

            if spatial_ratio > 0.70:

                return self.RISK_HIGH

            if motion_ratio > 0.70:

                return self.RISK_HIGH

            return self.RISK_LOW

        # ----------------------------------------------------
        # Strong appearance
        # ----------------------------------------------------

        if appearance_category == "strong":

            if spatial_ratio > 0.85:

                return self.RISK_HIGH

            if motion_ratio > 0.90:

                return self.RISK_HIGH

            return self.RISK_LOW

        return self.RISK_MEDIUM

    # ========================================================
    # STATUS
    # ========================================================

    def _status_from_risk(
        self,
        risk_level: str,
    ) -> str:

        if risk_level == self.RISK_LOW:

            return self.STATUS_PASS

        if risk_level == self.RISK_MEDIUM:

            return self.STATUS_REVIEW

        if risk_level == self.RISK_HIGH:

            return self.STATUS_HIGH_RISK

        return self.STATUS_INVALID

    # ========================================================
    # PRIMARY REASON
    # ========================================================

    @staticmethod
    def _primary_reason(
        reasons: list[str],
        matched: bool,
    ) -> str:

        if not reasons:

            return (
                "accepted_match"
                if matched
                else "rejected_match"
            )

        return reasons[0]

    # ========================================================
    # SUMMARY
    # ========================================================

    def get_summary(self) -> dict[str, Any]:
        """
        Return aggregate validation statistics.
        """

        results = self.match_results

        accepted = [
            result
            for result in results
            if result.matched
        ]

        rejected = [
            result
            for result in results
            if not result.matched
        ]

        evaluated = [
            result
            for result in results
            if result.appearance_evaluated
        ]

        valid_appearance = [
            result
            for result in evaluated
            if result.appearance_similarity
            >= 0.0
        ]

        strong = [
            result
            for result in valid_appearance
            if result.appearance_similarity
            >= self.strong_appearance_similarity
        ]

        normal = [
            result
            for result in valid_appearance
            if (
                self.normal_appearance_similarity
                <= result.appearance_similarity
                < self.strong_appearance_similarity
            )
        ]

        weak = [
            result
            for result in valid_appearance
            if (
                self.minimum_appearance_similarity
                <= result.appearance_similarity
                < self.normal_appearance_similarity
            )
        ]

        missing = [
            result
            for result in evaluated
            if result.appearance_similarity
            < 0.0
        ]

        not_evaluated = [
            result
            for result in results
            if not result.appearance_evaluated
        ]

        similarities = [
            result.appearance_similarity
            for result in valid_appearance
        ]

        accepted_similarities = [
            result.appearance_similarity
            for result in accepted
            if (
                result.appearance_evaluated
                and result.appearance_similarity
                >= 0.0
            )
        ]

        risky = [
            result
            for result in accepted
            if result.risk_level
            in {
                self.RISK_HIGH,
                self.RISK_CRITICAL,
            }
        ]

        # ----------------------------------------------------
        # V5.2:
        # Suspicious = accepted matches with actual
        # validator warnings.
        #
        # Matcher reasons do NOT count.
        # ----------------------------------------------------

        suspicious = [
            result
            for result in accepted
            if result.validation_warnings
        ]

        validation_warning_count = sum(
            len(
                result.validation_warnings
            )
            for result in results
        )

        matcher_diagnostic_count = sum(
            len(
                result.matcher_reasons
            )
            for result in results
        )

        # ----------------------------------------------------
        # Accepted appearance categories
        # ----------------------------------------------------

        accepted_strong = [
            result
            for result in accepted
            if (
                result.appearance_evaluated
                and result.appearance_similarity
                >= self.strong_appearance_similarity
            )
        ]

        accepted_normal = [
            result
            for result in accepted
            if (
                result.appearance_evaluated
                and self.normal_appearance_similarity
                <= result.appearance_similarity
                < self.strong_appearance_similarity
            )
        ]

        accepted_weak = [
            result
            for result in accepted
            if (
                result.appearance_evaluated
                and self.minimum_appearance_similarity
                <= result.appearance_similarity
                < self.normal_appearance_similarity
            )
        ]

        return {
            "version": self.VERSION,

            "candidates": len(results),

            "accepted_matches": len(
                accepted
            ),

            "rejected_matches": len(
                rejected
            ),

            "appearance": {
                "evaluated": len(
                    evaluated
                ),

                "not_evaluated": len(
                    not_evaluated
                ),

                "valid_comparisons": len(
                    valid_appearance
                ),

                "missing_embeddings": len(
                    missing
                ),

                "strong": len(
                    strong
                ),

                "normal": len(
                    normal
                ),

                "weak": len(
                    weak
                ),

                "average_similarity": (
                    self._average(
                        similarities
                    )
                ),

                "accepted_average_similarity": (
                    self._average(
                        accepted_similarities
                    )
                ),

                "accepted_strong": len(
                    accepted_strong
                ),

                "accepted_normal": len(
                    accepted_normal
                ),

                "accepted_weak": len(
                    accepted_weak
                ),
            },

            "risk": {
                "risky_matches": len(
                    risky
                ),

                "suspicious_matches": len(
                    suspicious
                ),

                "validation_warning_count": (
                    validation_warning_count
                ),

                "matcher_diagnostic_count": (
                    matcher_diagnostic_count
                ),

                "high_risk": sum(
                    1
                    for result in results
                    if result.risk_level
                    == self.RISK_HIGH
                ),

                "critical": sum(
                    1
                    for result in results
                    if result.risk_level
                    == self.RISK_CRITICAL
                ),
            },

            "identities": {
                "total": len(
                    self.identity_results
                ),

                "pass": sum(
                    1
                    for result
                    in self.identity_results.values()
                    if result.status
                    == self.STATUS_PASS
                ),

                "review": sum(
                    1
                    for result
                    in self.identity_results.values()
                    if result.status
                    == self.STATUS_REVIEW
                ),

                "high_risk": sum(
                    1
                    for result
                    in self.identity_results.values()
                    if result.status
                    == self.STATUS_HIGH_RISK
                ),

                "invalid": sum(
                    1
                    for result
                    in self.identity_results.values()
                    if result.status
                    == self.STATUS_INVALID
                ),
            },

            "thresholds": {
                "minimum_appearance_similarity": (
                    self.minimum_appearance_similarity
                ),

                "normal_appearance_similarity": (
                    self.normal_appearance_similarity
                ),

                "strong_appearance_similarity": (
                    self.strong_appearance_similarity
                ),

                "weak_spatial_ratio": (
                    self.weak_spatial_ratio
                ),

                "weak_motion_ratio": (
                    self.weak_motion_ratio
                ),

                "strong_spatial_ratio": (
                    self.strong_spatial_ratio
                ),

                "strong_motion_ratio": (
                    self.strong_motion_ratio
                ),

                "long_gap_ratio": (
                    self.long_gap_ratio
                ),

                "max_temporal_gap": (
                    self.max_temporal_gap
                ),

                "max_spatial_distance": (
                    self.max_spatial_distance
                ),

                "max_motion_difference": (
                    self.max_motion_difference
                ),
            },
        }

    # ========================================================
    # FULL REPORT
    # ========================================================

    def get_report(
        self,
    ) -> dict[str, Any]:
        """
        Return complete validation report.
        """

        summary = self.get_summary()

        recommendations = (
            self._build_recommendations()
        )

        return {
            "version": self.VERSION,

            "status": self._overall_status(),

            "summary": summary,

            "recommendation": (
                self._overall_recommendation()
            ),

            "recommendations": (
                recommendations
            ),

            "matches": [
                result.to_dict()
                for result
                in self.match_results
            ],

            "identities": [
                result.to_dict()
                for result
                in self.identity_results.values()
            ],
        }

    # ========================================================
    # OVERALL STATUS
    # ========================================================

    def _overall_status(
        self,
    ) -> str:
        """
        Determine overall validation status.
        """

        # Match-level critical
        if any(
            result.status
            == self.STATUS_INVALID
            for result in self.match_results
        ):

            return self.STATUS_INVALID

        # Match-level high risk
        if any(
            result.status
            == self.STATUS_HIGH_RISK
            for result in self.match_results
        ):

            return self.STATUS_HIGH_RISK

        # Match-level review
        if any(
            result.status
            == self.STATUS_REVIEW
            for result in self.match_results
        ):

            return self.STATUS_REVIEW

        # Identity-level critical
        if any(
            result.status
            == self.STATUS_INVALID
            for result in self.identity_results.values()
        ):

            return self.STATUS_INVALID

        # Identity-level high risk
        if any(
            result.status
            == self.STATUS_HIGH_RISK
            for result in self.identity_results.values()
        ):

            return self.STATUS_HIGH_RISK

        # Identity-level review
        if any(
            result.status
            == self.STATUS_REVIEW
            for result in self.identity_results.values()
        ):

            return self.STATUS_REVIEW

        return self.STATUS_PASS

    # ========================================================
    # RECOMMENDATION
    # ========================================================

    def _overall_recommendation(
        self,
    ) -> str:
        """
        Generate a high-level validation recommendation.
        """

        summary = self.get_summary()

        candidates = summary[
            "candidates"
        ]

        if candidates == 0:

            return (
                "NO MATCHES: no identity "
                "matching diagnostics were "
                "available for visual validation."
            )

        critical = summary[
            "risk"
        ]["critical"]

        high_risk = summary[
            "risk"
        ]["high_risk"]

        suspicious = summary[
            "risk"
        ]["suspicious_matches"]

        review = summary[
            "identities"
        ]["review"]

        # ----------------------------------------------------
        # Critical
        # ----------------------------------------------------

        if critical > 0:

            return (
                "CRITICAL: one or more identity "
                "assignments contain validation "
                "inconsistencies and require "
                "immediate visual inspection."
            )

        # ----------------------------------------------------
        # High risk
        # ----------------------------------------------------

        if high_risk > 0:

            return (
                "HIGH RISK: one or more accepted "
                "identity matches should be "
                "visually inspected."
            )

        # ----------------------------------------------------
        # Genuine suspicious matches
        # ----------------------------------------------------

        if suspicious > 0:

            return (
                "REVIEW: identity matching is "
                "generally usable, but some accepted "
                "matches contain validation warnings."
            )

        # ----------------------------------------------------
        # Identity-level review
        # ----------------------------------------------------

        if review > 0:

            return (
                "REVIEW: identity matching is "
                "generally usable, but some identities "
                "require additional inspection."
            )

        # ----------------------------------------------------
        # Clean
        # ----------------------------------------------------

        return (
            "EXCELLENT: appearance matching quality "
            "is strong and no significant visual "
            "validation risks were detected."
        )

    # ========================================================
    # RECOMMENDATIONS
    # ========================================================

    def _build_recommendations(
        self,
    ) -> list[str]:
        """
        Build actionable validation recommendations.
        """

        recommendations = []

        summary = self.get_summary()

        appearance = summary[
            "appearance"
        ]

        risk = summary[
            "risk"
        ]

        # ----------------------------------------------------
        # Missing embeddings
        # ----------------------------------------------------

        if appearance[
            "missing_embeddings"
        ] > 0:

            recommendations.append(
                "Some candidates reached appearance "
                "evaluation but had no valid embeddings. "
                "Inspect the OSNet embedding extraction "
                "pipeline."
            )

        # ----------------------------------------------------
        # Weak appearance
        # ----------------------------------------------------

        if appearance["weak"] > 0:

            recommendations.append(
                "Weak appearance matches were detected. "
                "Verify these identities visually before "
                "using them for final analytics."
            )

        # ----------------------------------------------------
        # Risky
        # ----------------------------------------------------

        if risk["risky_matches"] > 0:

            recommendations.append(
                "Risky accepted matches were detected. "
                "Inspect the corresponding track-to-"
                "identity assignments in the source video."
            )

        # ----------------------------------------------------
        # Suspicious
        # ----------------------------------------------------

        if risk[
            "suspicious_matches"
        ] > 0:

            recommendations.append(
                "Some accepted matches contain genuine "
                "validation warnings. Review the affected "
                "track-to-identity assignments."
            )

        # ----------------------------------------------------
        # Critical
        # ----------------------------------------------------

        if risk["critical"] > 0:

            recommendations.append(
                "Critical validation inconsistencies "
                "were detected. Do not treat the affected "
                "global identities as reliable until "
                "visually verified."
            )

        # ----------------------------------------------------
        # No appearance evaluation
        # ----------------------------------------------------

        if appearance[
            "not_evaluated"
        ] > 0:

            recommendations.append(
                "Some candidates were rejected before "
                "appearance evaluation. This is expected "
                "for hard geometry failures and should "
                "not be counted as missing embeddings."
            )

        # ----------------------------------------------------
        # Clean result
        # ----------------------------------------------------

        if not recommendations:

            recommendations.append(
                "No major visual validation issues "
                "were detected."
            )

        return recommendations

    # ========================================================
    # MATCH LOOKUP
    # ========================================================

    def get_match_results(
        self,
    ) -> list[dict[str, Any]]:
        """
        Return all match validation results.
        """

        return [
            result.to_dict()
            for result
            in self.match_results
        ]

    # ========================================================

    def get_risky_matches(
        self,
    ) -> list[dict[str, Any]]:
        """
        Return only HIGH and CRITICAL matches.
        """

        return [
            result.to_dict()
            for result
            in self.match_results
            if result.risk_level
            in {
                self.RISK_HIGH,
                self.RISK_CRITICAL,
            }
        ]

    # ========================================================

    def get_suspicious_matches(
        self,
    ) -> list[dict[str, Any]]:
        """
        Return accepted matches that contain
        genuine validation warnings.

        V5.2:

        Matcher diagnostic reasons alone do NOT qualify.
        """

        return [
            result.to_dict()
            for result
            in self.match_results
            if (
                result.matched
                and result.validation_warnings
            )
        ]

    # ========================================================

    def get_identity_results(
        self,
    ) -> list[dict[str, Any]]:
        """
        Return per-identity validation results.
        """

        return [
            result.to_dict()
            for result
            in self.identity_results.values()
        ]

    # ========================================================

    def get_high_risk_identities(
        self,
    ) -> list[dict[str, Any]]:
        """
        Return identities requiring visual inspection.
        """

        return [
            result.to_dict()
            for result
            in self.identity_results.values()
            if result.risk_level
            in {
                self.RISK_HIGH,
                self.RISK_CRITICAL,
            }
        ]

    # ========================================================
    # LOGGING
    # ========================================================

    def log_report(
        self,
    ) -> None:
        """
        Log the complete validation summary.
        """

        summary = self.get_summary()

        logger.info(
            "================================================"
        )

        logger.info(
            "IDENTITY VISUAL VALIDATION %s",
            self.VERSION.upper(),
        )

        logger.info(
            "================================================"
        )

        logger.info(
            "Status: %s",
            self._overall_status(),
        )

        logger.info(
            "Candidates: %d",
            summary["candidates"],
        )

        logger.info(
            "Accepted matches: %d",
            summary[
                "accepted_matches"
            ],
        )

        logger.info(
            "Rejected matches: %d",
            summary[
                "rejected_matches"
            ],
        )

        appearance = summary[
            "appearance"
        ]

        logger.info(
            "Appearance evaluated: %d",
            appearance[
                "evaluated"
            ],
        )

        logger.info(
            "Appearance not evaluated: %d",
            appearance[
                "not_evaluated"
            ],
        )

        logger.info(
            "Valid appearance comparisons: %d",
            appearance[
                "valid_comparisons"
            ],
        )

        logger.info(
            "Missing embeddings: %d",
            appearance[
                "missing_embeddings"
            ],
        )

        logger.info(
            "Strong appearance matches: %d",
            appearance[
                "strong"
            ],
        )

        logger.info(
            "Normal appearance matches: %d",
            appearance[
                "normal"
            ],
        )

        logger.info(
            "Weak appearance matches: %d",
            appearance[
                "weak"
            ],
        )

        logger.info(
            "Average appearance similarity: %.4f",
            appearance[
                "average_similarity"
            ],
        )

        logger.info(
            "Accepted appearance similarity: %.4f",
            appearance[
                "accepted_average_similarity"
            ],
        )

        logger.info(
            "Accepted strong appearance: %d",
            appearance[
                "accepted_strong"
            ],
        )

        logger.info(
            "Accepted normal appearance: %d",
            appearance[
                "accepted_normal"
            ],
        )

        logger.info(
            "Accepted weak appearance: %d",
            appearance[
                "accepted_weak"
            ],
        )

        risk = summary[
            "risk"
        ]

        logger.info(
            "Risky matches: %d",
            risk[
                "risky_matches"
            ],
        )

        logger.info(
            "Suspicious matches: %d",
            risk[
                "suspicious_matches"
            ],
        )

        logger.info(
            "Validation warnings: %d",
            risk[
                "validation_warning_count"
            ],
        )

        logger.info(
            "Matcher diagnostics: %d",
            risk[
                "matcher_diagnostic_count"
            ],
        )

        logger.info(
            "High-risk matches: %d",
            risk[
                "high_risk"
            ],
        )

        logger.info(
            "Critical matches: %d",
            risk[
                "critical"
            ],
        )

        logger.info(
            "Recommendation: %s",
            self._overall_recommendation(),
        )

        logger.info(
            "================================================"
        )

    # ========================================================
    # LOG RISKY MATCHES
    # ========================================================

    def log_risky_matches(
        self,
    ) -> None:
        """
        Log detailed information about risky matches.
        """

        risky = self.get_risky_matches()

        if not risky:

            logger.info(
                "No risky identity matches detected."
            )

            return

        logger.warning(
            "Found %d risky identity matches.",
            len(risky),
        )

        for result in risky:

            logger.warning(
                (
                    "RISKY MATCH | identity=%s "
                    "track=%s score=%.4f "
                    "appearance=%.4f "
                    "temporal_gap=%d "
                    "spatial=%.2f "
                    "motion=%.2f "
                    "risk=%s "
                    "reason=%s "
                    "warnings=%s"
                ),

                result[
                    "identity_id"
                ],

                result[
                    "track_id"
                ],

                result[
                    "score"
                ],

                result[
                    "appearance_similarity"
                ],

                result[
                    "temporal_gap"
                ],

                result[
                    "spatial_distance"
                ],

                result[
                    "motion_difference"
                ],

                result[
                    "risk_level"
                ],

                result[
                    "reason"
                ],

                result[
                    "validation_warnings"
                ],
            )

    # ========================================================
    # UTILITIES
    # ========================================================

    @staticmethod
    def _average(
        values: list[float],
    ) -> float:

        if not values:
            return 0.0

        return (
            sum(values)
            / len(values)
        )

    # ========================================================

    @staticmethod
    def _safe_float(
        value: Any,
        default: float = 0.0,
    ) -> float:

        try:

            result = float(value)

        except (
            TypeError,
            ValueError,
        ):

            return default

        return result

    # ========================================================

    @staticmethod
    def _safe_int(
        value: Any,
        default: int = 0,
    ) -> int:

        try:

            return int(value)

        except (
            TypeError,
            ValueError,
        ):

            return default


# ============================================================
# CONVENIENCE API
# ============================================================


def validate_identity_manager(
    manager: Any,
) -> dict[str, Any]:
    """
    Convenience function.

    Example
    -------

    validator = validate_identity_manager(manager)
    """

    validator = IdentityVisualValidator()

    return validator.validate_manager(
        manager
    )


# ============================================================


def validate_identity_diagnostics(
    diagnostics: Iterable[dict[str, Any]],
) -> dict[str, Any]:
    """
    Validate a list of GlobalIdentityManager match
    diagnostics.
    """

    validator = IdentityVisualValidator()

    validator.validate_diagnostics(
        diagnostics
    )

    return validator.get_report()


# ============================================================


def get_risky_identity_matches(
    manager: Any,
) -> list[dict[str, Any]]:
    """
    Convenience function returning only risky matches.
    """

    validator = IdentityVisualValidator()

    validator.validate_manager(
        manager
    )

    return validator.get_risky_matches()


# ============================================================


def get_identity_validation_report(
    manager: Any,
) -> dict[str, Any]:
    """
    Convenience function returning the complete report.
    """

    validator = IdentityVisualValidator()

    return validator.validate_manager(
        manager
    )