# Generated by Django 5.2.6 on 2026-07-27 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('team_type', models.CharField(choices=[('CLUB', 'Club'), ('NATIONAL', 'National Team')], default='CLUB', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('primary_color', models.CharField(help_text='Hex color code (e.g. #FF0000)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Hex color code (e.g. #FFFFFF)', max_length=7, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('coach', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='teams_name_12b53a_idx'), models.Index(fields=['country'], name='teams_country_56e7ce_idx'), models.Index(fields=['league'], name='teams_league_856e85_idx')],
            },
        ),
    ]
