# Generated by Django 5.2.6 on 2026-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveSmallIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('passes_attempted', models.PositiveSmallIntegerField(default=0)),
                ('passes_completed', models.PositiveSmallIntegerField(default=0)),
                ('pass_accuracy', models.FloatField(default=0)),
                ('key_passes', models.PositiveSmallIntegerField(default=0)),
                ('dribbles_completed', models.PositiveSmallIntegerField(default=0)),
                ('tackles', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('clearances', models.PositiveSmallIntegerField(default=0)),
                ('fouls_committed', models.PositiveSmallIntegerField(default=0)),
                ('fouls_suffered', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('offsides', models.PositiveSmallIntegerField(default=0)),
                ('distance_covered', models.FloatField(default=0, help_text='Distance in meters')),
                ('top_speed', models.FloatField(default=0, help_text='km/h')),
                ('average_speed', models.FloatField(default=0, help_text='km/h')),
                ('xg', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='players.player')),
            ],
            options={
                'db_table': 'player_statistics',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['match'], name='player_stat_match_i_4b2a62_idx'), models.Index(fields=['player'], name='player_stat_player__ac7c1a_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.FloatField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shots_on_target', models.PositiveSmallIntegerField(default=0)),
                ('passes_attempted', models.PositiveSmallIntegerField(default=0)),
                ('passes_completed', models.PositiveSmallIntegerField(default=0)),
                ('pass_accuracy', models.FloatField(default=0)),
                ('corners', models.PositiveSmallIntegerField(default=0)),
                ('offsides', models.PositiveSmallIntegerField(default=0)),
                ('fouls', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('xg', models.FloatField(default=0)),
                ('total_distance', models.FloatField(default=0, help_text='Meters')),
                ('average_team_speed', models.FloatField(default=0, help_text='km/h')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.team')),
            ],
            options={
                'db_table': 'team_statistics',
                'ordering': ['match'],
                'indexes': [models.Index(fields=['match'], name='team_statis_match_i_d3a25f_idx'), models.Index(fields=['team'], name='team_statis_team_id_bfd41a_idx')],
                'unique_together': {('match', 'team')},
            },
        ),
    ]
