# Generated by Django 5.2.6 on 2026-07-27 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('MATCH', 'Match Report'), ('PLAYER', 'Player Report'), ('TEAM', 'Team Report')], default='MATCH', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='reports/pdfs/')),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.match')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match'], name='reports_match_i_983bd8_idx'), models.Index(fields=['report_type'], name='reports_report__ff8b25_idx')],
            },
        ),
    ]
