# Generated by Django 5.2.6 on 2026-08-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_trackplayeridentification'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('match', 'report_type')},
        ),
    ]
