# Generated by Django 5.2.6 on 2026-07-27 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('match_date', models.DateField()),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('competition', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(default=90, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tracking_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('ball_tracking_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('passes_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('shots_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('events_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('player_stats_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('team_stats_csv', models.FileField(blank=True, null=True, upload_to='matches/csv/')),
                ('match_report', models.FileField(blank=True, null=True, upload_to='matches/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='matches.match')),
            ],
            options={
                'db_table': 'match_files',
            },
        ),
        migrations.CreateModel(
            name='MatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(upload_to='matches/videos/')),
                ('annotated_video', models.FileField(blank=True, null=True, upload_to='matches/annotated/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='matches/thumbnails/')),
                ('video_duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('resolution_width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_height', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='matches.match')),
            ],
            options={
                'db_table': 'match_videos',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date'], name='matches_match_d_701e65_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matches_status_639056_idx'),
        ),
    ]
