# Generated by Django 5.2.6 on 2026-08-01 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_gk_kit_color',
            field=models.CharField(blank=True, help_text='Hex color worn by away team goalkeeper this match', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_kit_color',
            field=models.CharField(blank=True, help_text='Hex color worn by away team outfield players this match', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_gk_kit_color',
            field=models.CharField(blank=True, help_text='Hex color worn by home team goalkeeper this match', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_kit_color',
            field=models.CharField(blank=True, help_text='Hex color worn by home team outfield players this match', max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('side', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], max_length=4)),
                ('player_name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=5)),
                ('is_starting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
                ('player', models.ForeignKey(blank=True, help_text='Linked automatically if a roster Player with this jersey number already exists on the team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_lineups', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineups', to='teams.team')),
            ],
            options={
                'db_table': 'match_lineups',
                'ordering': ['match', 'side', 'jersey_number'],
                'indexes': [models.Index(fields=['match'], name='match_lineu_match_i_503785_idx'), models.Index(fields=['team'], name='match_lineu_team_id_5be7db_idx')],
                'unique_together': {('match', 'side', 'jersey_number')},
            },
        ),
    ]
