# Generated by Django 5.2.6 on 2026-08-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_gk_kit_color_match_away_kit_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_frame', models.PositiveIntegerField(help_text='Frame index (0-based) the 4 points below were picked on')),
                ('points', models.JSONField(help_text="Exactly 4 dicts: {'landmark_id', 'pixel_x', 'pixel_y', 'pitch_x', 'pitch_y'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='matches.match')),
            ],
            options={
                'db_table': 'match_calibrations',
            },
        ),
    ]
