# Generated by Django 5.2.6 on 2026-08-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchcalibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlayerIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.PositiveIntegerField(help_text="Stitched tracklet's track_id, as it appears in player_tracking_csv/player_stats_csv for this match")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineup_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_identifications', to='matches.matchlineup')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_identifications', to='matches.match')),
            ],
            options={
                'db_table': 'track_player_identifications',
                'unique_together': {('match', 'lineup_entry'), ('match', 'track_id')},
            },
        ),
    ]
