# Generated by Django 5.2.6 on 2026-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_trackplayeridentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackplayeridentification',
            name='is_auto_assigned',
            field=models.BooleanField(default=False, help_text='True = system guess, not yet confirmed by a human. False = a person explicitly chose this on /identify/.'),
        ),
    ]
