# Generated by Django 5.2.6 on 2026-09-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_trackplayeridentification_is_auto_assigned'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_own_goal', models.BooleanField(default=False, help_text='If True, scorer (if set) belongs to the side OPPOSING `team`')),
                ('minute', models.PositiveSmallIntegerField(blank=True, help_text='Match minute, if known — informational only, not used in any scoring logic', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match')),
                ('scorer', models.ForeignKey(blank=True, help_text='Optional — a goal can be logged before the scorer is confirmed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_scored', to='matches.matchlineup')),
                ('team', models.ForeignKey(help_text='The team credited on the scoreboard for this goal', on_delete=django.db.models.deletion.CASCADE, related_name='match_goals', to='teams.team')),
            ],
            options={
                'db_table': 'match_goals',
                'ordering': ['match', 'minute', 'created_at'],
                'indexes': [models.Index(fields=['match'], name='match_goals_match_i_b89b30_idx')],
            },
        ),
    ]
