# Generated by Django 5.2.6 on 2026-09-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchcalibration',
            options={'ordering': ['match', 'calibration_frame']},
        ),
        migrations.AlterField(
            model_name='matchcalibration',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='matches.match'),
        ),
        migrations.AlterUniqueTogether(
            name='matchcalibration',
            unique_together={('match', 'calibration_frame')},
        ),
        migrations.AddIndex(
            model_name='matchcalibration',
            index=models.Index(fields=['match'], name='match_calib_match_i_d86506_idx'),
        ),
    ]
