# Generated by Django 5.2.6 on 2026-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_matchcalibration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcalibration',
            name='points',
            field=models.JSONField(help_text="4 or more dicts: {'landmark_id', 'pixel_x', 'pixel_y', 'pitch_x', 'pitch_y'}"),
        ),
    ]
