# Generated by Django 5.2.6 on 2026-10-06 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_matchcalibration_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgoal',
            name='assistant',
            field=models.ForeignKey(blank=True, help_text='Optional — player who provided the assist for this goal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_assisted', to='matches.matchlineup'),
        ),
    ]
